name: Build application docker image and push to Harbor
on:
  push:
    tags:
      - '*'

jobs:
  epoxy-logstash:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for getting GitHub OIDC Token (for sigstore authentication)
    steps:
      - name: Get the git tag
        id: get_tag
        shell: bash
        run: |
          echo "TAG=$(echo $GITHUB_REF_NAME)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3.5.2
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: v2.2.1
      - name: Check install
        run: cosign version
      - name: Build&Push container image
        id: build-and-push
        run: |
          IMAGE_TAG="harbor.whalebone.io/resolver/logrotate:${{ steps.get_tag.outputs.TAG }}"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.whalebone.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build . --file Dockerfile --tag "$IMAGE_TAG"
          docker push "$IMAGE_TAG"
          docker logout harbor.whalebone.io
          echo "IMAGE_HASH=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_TAG)" >> $GITHUB_OUTPUT
      - name: Sign image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.whalebone.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          cosign sign --yes ${{ steps.build-and-push.outputs.IMAGE_HASH }}
          docker logout harbor.whalebone.io
      - name: Verify image
        run: |
          # TODO: Identity should exactly match instead of accepting all identities.
          cosign verify ${{ steps.build-and-push.outputs.IMAGE_HASH }} --certificate-identity-regexp='.*' --certificate-oidc-issuer='https://token.actions.githubusercontent.com'
